name: Dev CI

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "lts"
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Bootstrap environment
        run: ./lib/env-loader.sh ci
      - name: Lint
        run: npx nx run-many --target=lint --all
      - name: Test
        run: npx nx run-many --target=test --all
