name: Logging tests

on:
  pull_request:
  push:
    branches:
      - feature/**
      - main

jobs:
  logging-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python for uv
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install and configure uv
        run: |
          set -euo pipefail
          python -m pip install --user --upgrade pipx
          python -m pipx ensurepath
          export PATH="$HOME/.local/bin:$PATH"
          pipx install uv
          uv venv .venv --python 3.12
          echo "VIRTUAL_ENV=$PWD/.venv" >> "$GITHUB_ENV"
          echo "$PWD/.venv/bin" >> "$GITHUB_PATH"
      - name: Verify Python venv
        run: |
          set -euo pipefail
          which python
          python --version
      - name: Install Python dependencies
        run: |
          set -euo pipefail
          uv pip install -r requirements.txt

      - name: Start mock OTLP receiver
        run: |
          set -x
          echo "Python executable: $(which python3)"
          echo "Python version: $(python3 --version)"
          echo "PWD: $(pwd)"
          echo "Listing tests/logging:"; ls -la tests/logging || true
          echo "Starting mock OTLP receiver..."
          chmod +x tests/logging/mock_otlp_receiver.py
          python3 tests/logging/mock_otlp_receiver.py --ports 43215 51417 --payload-dir /tmp/otlp-test --pid-file /tmp/otlp-test/pids.txt > /tmp/otlp-receiver.log 2>&1 &
          RECEIVER_PID=$!
          echo $RECEIVER_PID > /tmp/otlp-test/receiver.pid
          echo "Mock receiver started with PID: $RECEIVER_PID"

          # Wait for the receiver to be ready (up to 30 seconds)
          for i in {1..30}; do
            if grep -q "All servers started" /tmp/otlp-receiver.log 2>/dev/null; then
              echo "Mock receiver is ready!"
              sed -n '1,200p' /tmp/otlp-receiver.log || true
              break
            fi
            if [ $i -eq 30 ]; then
              echo "ERROR: Mock receiver did not start within 30 seconds"
              echo "--- /tmp/otlp-receiver.log (tail) ---"
              tail -n +1 /tmp/otlp-receiver.log || echo "No log file found"
              echo "--- /tmp/otlp-test contents ---"
              ls -la /tmp/otlp-test || true
              exit 1
            fi
            sleep 1
          done

      - name: Run unit OTLP payload test
        run: |
          chmod +x tests/logging/test_build_otlp_payload.sh
          ./tests/logging/test_build_otlp_payload.sh

      - name: Run integration OTLP test
        run: |
          chmod +x tests/logging/test_integration_otlp_runner.sh
          ./tests/logging/test_integration_otlp_runner.sh

      - name: Stop mock OTLP receiver
        if: always()
        run: |
          set -x || true

          echo "---- Dumping receiver log ----"
          if [ -f /tmp/otlp-receiver.log ]; then
            sed -n '1,200p' /tmp/otlp-receiver.log || true
          else
            echo "No /tmp/otlp-receiver.log found"
          fi

          echo "---- Received payloads ----"
          if ls /tmp/otlp-test/payload_*.json 1> /dev/null 2>&1; then
            for f in /tmp/otlp-test/payload_*.json; do
              echo "File: $f"
              head -n 200 "$f" || true
            done
          else
            echo "No payload files found in /tmp/otlp-test"
            ls -la /tmp/otlp-test || true
          fi

          if [ -f /tmp/otlp-test/receiver.pid ]; then
            PID=$(cat /tmp/otlp-test/receiver.pid)
            echo "Killing receiver PID: $PID"
            if kill -0 $PID 2>/dev/null; then
              kill $PID || true
              sleep 1
              kill -9 $PID || true
            fi
          fi
          pkill -f "mock_otlp_receiver.py" || true
