name: Logging tests

on:
  pull_request:
  push:
    branches:
      - feature/**
      - main

jobs:
  logging-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Run unit OTLP payload test
        run: |
          chmod +x tests/logging/test_build_otlp_payload.sh
          ./tests/logging/test_build_otlp_payload.sh

      - name: Run integration OTLP test
        run: |
          chmod +x tests/logging/test_integration_otlp_runner.sh
          ./tests/logging/test_integration_otlp_runner.sh
