name: Logging tests

on:
  pull_request:
  push:
    branches:
      - feature/**
      - main

jobs:
  logging-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Start mock OTLP receiver
        run: |
          echo "Python version: $(python3 --version)"
          echo "Starting mock OTLP receiver..."
          chmod +x tests/logging/mock_otlp_receiver.py
          python3 tests/logging/mock_otlp_receiver.py --ports 43215 51417 --payload-dir /tmp/otlp-test --pid-file /tmp/otlp-test/pids.txt > /tmp/otlp-receiver.log 2>&1 &
          RECEIVER_PID=$!
          echo $RECEIVER_PID > /tmp/otlp-test/receiver.pid
          echo "Mock receiver started with PID: $RECEIVER_PID"

          # Wait for the receiver to be ready (up to 10 seconds)
          for i in {1..10}; do
            if grep -q "All servers started" /tmp/otlp-receiver.log 2>/dev/null; then
              echo "Mock receiver is ready!"
              cat /tmp/otlp-receiver.log
              break
            fi
            if [ $i -eq 10 ]; then
              echo "ERROR: Mock receiver did not start within 10 seconds"
              cat /tmp/otlp-receiver.log || echo "No log file found"
              exit 1
            fi
            sleep 1
          done

      - name: Run unit OTLP payload test
        run: |
          chmod +x tests/logging/test_build_otlp_payload.sh
          ./tests/logging/test_build_otlp_payload.sh

      - name: Run integration OTLP test
        run: |
          chmod +x tests/logging/test_integration_otlp_runner.sh
          ./tests/logging/test_integration_otlp_runner.sh

      - name: Stop mock OTLP receiver
        if: always()
        run: |
          if [ -f /tmp/otlp-test/receiver.pid ]; then
            PID=$(cat /tmp/otlp-test/receiver.pid)
            if kill -0 $PID 2>/dev/null; then
              kill $PID
              # Wait a moment for graceful shutdown
              sleep 1
              # Force kill if still running
              if kill -0 $PID 2>/dev/null; then
                kill -9 $PID
              fi
            fi
          fi
          # Clean up any remaining processes using the ports
          pkill -f "mock_otlp_receiver.py" || true
