name: Main Release

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "lts"
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Bootstrap environment
        run: ./lib/env-loader.sh ci
      - name: Lint
        run: npx nx run-many --target=lint --all
      - name: Test
        run: npx nx run-many --target=test --all
      - name: Build
        run: npx nx run-many --target=build --all
      - name: Deploy
        run: npx nx run-many --target=deploy --all
