name: Main Release

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "lts"
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Bootstrap environment
        run: ./lib/env-loader.sh ci
      - name: Install uv & Python venv (CI)
        run: |
          if python3.12 -V >/dev/null 2>&1; then
            PYTHON_EXEC=python3.12
          else
            PYTHON_EXEC=python3
          fi
          echo "PYTHON_EXEC=$PYTHON_EXEC" >> "$GITHUB_ENV"

          # Install pipx using the chosen Python and ensure it's usable
          # Note: `pipx ensurepath` can be non-fatal in runners because it may
          # not be able to modify login shell profiles; we warn but continue.
          "$PYTHON_EXEC" -m pip install --user --upgrade pipx
          "$PYTHON_EXEC" -m pipx ensurepath || echo "⚠️ pipx ensurepath failed; PATH may need adjustment"
          "$PYTHON_EXEC" -m pipx install uv

          # Extract Python version from PYTHON_EXEC for uv commands (keeps workflow aligned with runner Python)
          PYTHON_VERSION=$("$PYTHON_EXEC" -V | cut -d' ' -f2 | cut -d'.' -f1,2)
          uv python install "$PYTHON_VERSION" >/dev/null 2>&1

          if [ ! -d .venv ]; then
            uv venv .venv --python "$PYTHON_VERSION" >/dev/null 2>&1 || "$PYTHON_EXEC" -m venv .venv
          fi

          echo "VIRTUAL_ENV=$PWD/.venv" >> "$GITHUB_ENV"
          echo "$PWD/.venv/bin" >> "$GITHUB_PATH"

          # Verify the virtual environment is properly activated
          echo "Python executable: $(which "$PYTHON_EXEC")"
          echo "Python version: $("$PYTHON_EXEC" --version)"
          echo "Virtual environment: $VIRTUAL_ENV"
      - name: Lint
        run: npx nx run-many --target=lint --all
      - name: Test
        run: npx nx run-many --target=test --all
      - name: Logging Check
        run: npx nx run-many --target=logging --all
      - name: Build
        run: npx nx run-many --target=build --all
      - name: Deploy
        run: npx nx run-many --target=deploy --all
