name: Stage CI

on:
  push:
    branches: ["stage"]
  workflow_dispatch:

jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "lts"
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Bootstrap environment
        run: ./lib/env-loader.sh ci
      - name: Install uv & Python venv (CI)
        run: |
          if command -v uv >/dev/null 2>&1; then
            echo "uv already available"
          else
            python3 -m pip install --user --upgrade pipx || true
            python3 -m pipx ensurepath || true
            python3 -m pipx install uv || true
          fi
          if python3.12 -V >/dev/null 2>&1; then
            PYTHON_EXEC=python3.12
          else
            PYTHON_EXEC=python3
          fi
          uv python install 3.12 >/dev/null 2>&1 || true
          uv venv .venv -p 3.12 --managed-python || uv venv .venv || python3 -m venv .venv || true
          . .venv/bin/activate || true
      - name: Lint
        run: npx nx run-many --target=lint --all
      - name: Test
        run: npx nx run-many --target=test --all
      - name: Build
        run: npx nx run-many --target=build --all
