name: Stage CI

on:
  push:
    branches: ["stage"]
  workflow_dispatch:

jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "lts"
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Bootstrap environment
        run: ./lib/env-loader.sh ci
      - name: Install uv & Python venv (CI)
        run: |
          if python3.12 -V >/dev/null 2>&1; then
            PYTHON_EXEC=python3.12
          else
            PYTHON_EXEC=python3
          fi
          echo "PYTHON_EXEC=$PYTHON_EXEC" >> "$GITHUB_ENV"

          $PYTHON_EXEC -m pip install --user --upgrade pipx || true
          $PYTHON_EXEC -m pipx ensurepath || true
          $PYTHON_EXEC -m pipx install uv || true

          uv python install 3.12 >/dev/null 2>&1 || true

          if [ ! -d .venv ]; then
            uv venv .venv --python 3.12 >/dev/null 2>&1 || $PYTHON_EXEC -m venv .venv || true
          fi

          echo "VIRTUAL_ENV=$PWD/.venv" >> "$GITHUB_ENV"
          echo "$PWD/.venv/bin" >> "$GITHUB_PATH"
      - name: Lint
        run: npx nx run-many --target=lint --all
      - name: Test
        run: npx nx run-many --target=test --all
      - name: Build
        run: npx nx run-many --target=build --all
